-- phpMyAdmin SQL Dump
-- version 4.7.1
-- https://www.phpmyadmin.net/
--
-- Hôte : sql7.freemysqlhosting.net
-- Généré le :  lun. 02 juil. 2018 à 08:09
-- Version du serveur :  5.5.58-0ubuntu0.14.04.1
-- Version de PHP :  7.0.30-0ubuntu0.16.04.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `sql7244905`
--

-- --------------------------------------------------------

--
-- Structure de la table `attractions`
--

CREATE TABLE `attractions` (
  `ID` int(11) NOT NULL,
  `THEME` varchar(30) DEFAULT NULL,
  `NOM` varchar(100) DEFAULT NULL,
  `IMAGE` varchar(200) NOT NULL DEFAULT '',
  `DESCRIPTIF` varchar(2000) NOT NULL,
  `AGE` int(11) NOT NULL,
  `OUVERTURE` time NOT NULL,
  `FERMETURE` time NOT NULL,
  `ACCESSIBILITE` varchar(20) NOT NULL,
  `LAT` double DEFAULT NULL,
  `LNG` double DEFAULT NULL,
  `EXCITATION` int(11) DEFAULT NULL,
  `image_guide` varchar(200) DEFAULT NULL,
  `paroles_guide` varchar(1000) DEFAULT NULL,
  `accueil_guide` varchar(100) DEFAULT NULL,
  `pointeur` varchar(200) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Déchargement des données de la table `attractions`
--

INSERT INTO `attractions` (`ID`, `THEME`, `NOM`, `IMAGE`, `DESCRIPTIF`, `AGE`, `OUVERTURE`, `FERMETURE`, `ACCESSIBILITE`, `LAT`, `LNG`, `EXCITATION`, `image_guide`, `paroles_guide`, `accueil_guide`, `pointeur`) VALUES
(2, 'love', 'The Sex Palace Peep Show', 'https://www.holland.com/upload_mm/c/2/3/21113_fullimage_Amsterdam-Brouwersgracht.jpg', 'The Sex Palace Peep Show est le dernier est un théâtre dans lequel le visiteur payant peut voir une personne qui prend des poses sexuelles explicites. Il offre une variété de spectacles sexuels qui peuvent être vus à partir d\'une petite cabine de couleur rose. Le visiteur doit insérer quelques euros pour commencer le spectacle de divertissement érotique. Le client paie par minute. Ici, c\'est deux euros par minute.\r\n', 25, '20:00:00', '23:00:00', 'Oui', 52.369177, 4.880908, 2, 'dave', 'Dag Dag c’est moi Dave le roi du Disco mais aussi le prince de la\r\nnuit et de la controverse. Je serais ton humble guide pour t’ouvrir\r\nles portes des bouis-bouis les plus sulfureux de Dam Park. Prépare\r\nta tunique de cuir et ton lubrifiant, cela ne va pas que suinter ce\r\nsoir!!!!!!\r\n« Vanina, rappelle-toi\r\nQue je ne suis rien sans toi\r\nVanina si tu m\'oublies »', 'Vanina ah ah vanina ah ah!!!', './images/markers/loveB.svg'),
(3, 'love', 'La Casa Rosso', 'https://media-cdn.tripadvisor.com/media/photo-s/12/73/34/92/casa-rosso-on-oudezijds.jpg', 'Rejoindre la légende demande du courage. Et pour affronter le Cheval de Troie, il en faut beaucoup !\r\nDans cette nacelle perchée à plus de 12 mètres de hauteur, vous virevoltez et voltigez avec un seul objectif : rester bien cramponné.\r\nNe vous inquiétez pas, les turbulences sont de courte durée et vous en sortez avec plus de rires que de peurs.', 18, '19:00:00', '23:00:00', 'Oui', 52.369649, 4.907001, 3, 'dave', 'Dag Dag c’est moi Dave le roi du Disco mais aussi le prince de la\r\nnuit et de la controverse. Je serais ton humble guide pour t’ouvrir\r\nles portes des bouis-bouis les plus sulfureux de Dam Park. Prépare\r\nta tunique de cuir et ton lubrifiant, cela ne va pas que suinter ce\r\nsoir!!!!!!\r\n« Vanina, rappelle-toi\r\nQue je ne suis rien sans toi\r\nVanina si tu m\'oublies »', 'Vanina ah ah vanina ah ah!!!', './images/markers/loveB.svg'),
(4, 'love', 'Chickita\'s Sex Paradijs', 'https://c1.staticflickr.com/6/5166/5231030888_5c10053147_b.jpg', 'Voyager vers Chickita\'s Sex Paradijs à Amsterdam n\'a jamais été aussi facile. Des montées et des descentes s\'enchaînent en douceur… Nombreux effets à prévoir : rires, hurlements et papillons dans le ventre.', 18, '09:00:00', '19:00:00', 'Oui', 52.375937, 4.89919, 2, 'dave', 'Dag Dag c’est moi Dave le roi du Disco mais aussi le prince de la\r\nnuit et de la controverse. Je serais ton humble guide pour t’ouvrir\r\nles portes des bouis-bouis les plus sulfureux de Dam Park. Prépare\r\nta tunique de cuir et ton lubrifiant, cela ne va pas que suinter ce\r\nsoir!!!!!!\r\n« Vanina, rappelle-toi\r\nQue je ne suis rien sans toi\r\nVanina si tu m\'oublies »', 'Vanina ah ah vanina ah ah!!!', './images/markers/loveB.svg'),
(5, 'love', 'Le Palais des mains baladeuses', 'http://thecoolhunter.net/wp-content/uploads/2016/08/brass_hands1.jpg', 'Grand palais aux milles mains. Elles sortent de tous les mûrs pour vous caresser sensuellement. Venez habiller léger pour plus de sensations. \r\n', 18, '10:00:00', '18:00:00', 'Oui', 52.378766, 4.887431, 3, 'dave', 'Dag Dag c’est moi Dave le roi du Disco mais aussi le prince de la\r\nnuit et de la controverse. Je serais ton humble guide pour t’ouvrir\r\nles portes des bouis-bouis les plus sulfureux de Dam Park. Prépare\r\nta tunique de cuir et ton lubrifiant, cela ne va pas que suinter ce\r\nsoir!!!!!!\r\n« Vanina, rappelle-toi\r\nQue je ne suis rien sans toi\r\nVanina si tu m\'oublies »', 'Vanina ah ah vanina ah ah!!!', './images/markers/loveB.svg'),
(6, 'love', 'La maison aux milles uniformes', 'http://femmedinfluence.fr/wp-content/uploads/2016/06/air-france-uniforme-gilles-tour%C3%A9.png', 'Les pompiers et les infirmières n’ont jamais arrêté d’avoir la côte. L’attrait de l’uniforme et du pouvoir reste un mystère pour certains, mais un aphrodisiaque pour d’autres. Si votre moitié ne travaille pas dans une caserne, ou un hôpital, pensez alors à la maison aux milles uniformes pour essayer nos jeux de rôles.\r\n', 22, '16:00:00', '23:00:00', 'Oui', 52.372059, 4.880135, 1, 'dave', 'Dag Dag c’est moi Dave le roi du Disco mais aussi le prince de la\r\nnuit et de la controverse. Je serais ton humble guide pour t’ouvrir\r\nles portes des bouis-bouis les plus sulfureux de Dam Park. Prépare\r\nta tunique de cuir et ton lubrifiant, cela ne va pas que suinter ce\r\nsoir!!!!!!\r\n« Vanina, rappelle-toi\r\nQue je ne suis rien sans toi\r\nVanina si tu m\'oublies »', 'Vanina ah ah vanina ah ah!!!', './images/markers/loveB.svg'),
(7, 'love', 'Le boudoir des petits trous', 'http://www.thegrumpyoldlimey.com/images/buildings/hole_main.jpg', 'Quel point en commun entre un passionné de golf et de gruyère ? Les trous. Amateur de petits trous, cette attraction est faite pour vous. Même les professionnels trouveront un trou à leur goût dans laquelle on entre et on sort.  Venez découvrir ce labyrinthe géant composé de tunnels et ponts.', 26, '17:00:00', '22:00:00', 'Oui', 52.375727, 4.908717, 2, 'dave', 'Dag Dag c’est moi Dave le roi du Disco mais aussi le prince de la\r\nnuit et de la controverse. Je serais ton humble guide pour t’ouvrir\r\nles portes des bouis-bouis les plus sulfureux de Dam Park. Prépare\r\nta tunique de cuir et ton lubrifiant, cela ne va pas que suinter ce\r\nsoir!!!!!!\r\n« Vanina, rappelle-toi\r\nQue je ne suis rien sans toi\r\nVanina si tu m\'oublies »', 'Vanina ah ah vanina ah ah!!!', './images/markers/loveB.svg'),
(8, 'art', 'La chambre de Van Gogh', 'http://p8.storage.canalblog.com/80/78/247924/10534849_p.jpg', 'Suffocation d’un lieu étroit dans lequel vous rencontrerez le célèbre peintre à l’oreille coupé. En tête à tête avec le personnage, vous pouvez apprendre les techniques traditionnelles hollandaises de peinture ou tout simplement avoir une conversation avec le maître hollandais.', 12, '09:00:00', '20:00:00', 'Oui', 52.385158, 4.889148, 1, 'mata', 'Mijn naam is Mata Ari, tu as certainement déjà entendu mon nom mais\r\ntu ne sais pas du tout qui je suis. Alors oui je me suis faite fusillée\r\npour espionnage pendant la Première Guerre mondiale, mais je suis\r\naussi une danseuse et une courtisane de renom. Mon goût pour la\r\nculture est sans équivoque, mes relations et ma faculté d\'écouter\r\naux portes ou de séduire pour obtenir des informations\r\nconfidentielles font de moi une bible de connaissance. Je serais ton\r\nguide, ta compteuse de bonnes aventures, à travers tous les lieux de \r\nstimulations et de controverses culturelles.', 'AiiiiiAIIIIIiiiiiAIIiiiiiiii!!!!!', './images/markers/artB.svg'),
(9, 'art', 'Le grenier de Rembrandt\r\n', 'https://i.pinimg.com/originals/94/d6/7f/94d67fc08be61ddba53d2352fd245900.png', 'Visite avec audio guide gratuit disponible en Français. Peu de monde, entrée rapide dans la maison musée. Le point fort de la visite est la démonstration sur la composition et réalisation des peintures de l\'époque par une intervenante passionnée et souriante. \r\nLa maison est une \"reconstitution\" d\'après documents retrouvés.', 6, '11:00:00', '19:00:00', 'Oui', 52.374601, 4.896143, 1, 'mata', 'Mijn naam is Mata Ari, tu as certainement déjà entendu mon nom mais\r\ntu ne sais pas du tout qui je suis. Alors oui je me suis faite fusillée\r\npour espionnage pendant la Première Guerre mondiale, mais je suis\r\naussi une danseuse et une courtisane de renom. Mon goût pour la\r\nculture est sans équivoque, mes relations et ma faculté d\'écouter\r\naux portes ou de séduire pour obtenir des informations\r\nconfidentielles font de moi une bible de connaissance. Je serais ton\r\nguide, ta compteuse de bonnes aventures, à travers tous les lieux de \r\nstimulations et de controverses culturelles.', 'AiiiiiAIIIIIiiiiiAIIiiiiiiii!!!!!', './images/markers/artB.svg'),
(10, 'art', 'Le labyrinthe infernal Willet', 'https://media-cdn.tripadvisor.com/media/photo-s/07/3d/da/29/creuse.jpg', 'Il s\'agit d\'une coquette maison historique aménagée au centre d’un grand labyrinthe arborée. Des milliers de chemins mais un seul itinéraire pour atteindre cette charmante demeure. A l’arrivée, vous trouverez un grand banquet de fruits et de fromages.', 6, '08:00:00', '18:00:00', 'Oui', 52.374542, 4.899447, 3, 'mata', 'Mijn naam is Mata Ari, tu as certainement déjà entendu mon nom mais\r\ntu ne sais pas du tout qui je suis. Alors oui je me suis faite fusillée\r\npour espionnage pendant la Première Guerre mondiale, mais je suis\r\naussi une danseuse et une courtisane de renom. Mon goût pour la\r\nculture est sans équivoque, mes relations et ma faculté d\'écouter\r\naux portes ou de séduire pour obtenir des informations\r\nconfidentielles font de moi une bible de connaissance. Je serais ton\r\nguide, ta compteuse de bonnes aventures, à travers tous les lieux de \r\nstimulations et de controverses culturelles.', '', './images/markers/artB.svg'),
(11, 'art', 'La maison du polaroïd', 'http://www.goldenmoustache.com/wp-content/uploads/2013/08/polaroid-geant-rue-capturer-joie.jpg', 'Installations expérimentales de photographies de grands artistes et mise à disposition de nombreux appareils pour se prendre en selfies et les partager sur de grands écrans en LED clignotant. L’occasion d’immortaliser votre passage dans le plus grand parc d’attraction hollandais.', 14, '10:00:00', '19:00:00', 'Non', 52.368673, 4.88889, 3, 'mata', 'Mijn naam is Mata Ari, tu as certainement déjà entendu mon nom mais\r\ntu ne sais pas du tout qui je suis. Alors oui je me suis faite fusillée\r\npour espionnage pendant la Première Guerre mondiale, mais je suis\r\naussi une danseuse et une courtisane de renom. Mon goût pour la\r\nculture est sans équivoque, mes relations et ma faculté d\'écouter\r\naux portes ou de séduire pour obtenir des informations\r\nconfidentielles font de moi une bible de connaissance. Je serais ton\r\nguide, ta compteuse de bonnes aventures, à travers tous les lieux de \r\nstimulations et de controverses culturelles.', 'AiiiiiAIIIIIiiiiiAIIiiiiiiii!!!!!', './images/markers/artB.svg'),
(12, 'art', 'Moco & Banksy Museum ', 'https://s3.amazonaws.com/rezgo/16752/110632/152734.jpg', 'En ce moment le musée est dédié sur 2 étages a Banksy et la visite est vraiment sympa ! Comptez une petite heure pour en faire le tour ! Toutes oeuvres principales de Banksy y sont présentées. ', 6, '10:00:00', '19:00:00', 'Oui', 52.37895, 4.896046, NULL, 'mata', 'Mijn naam is Mata Ari, tu as certainement déjà entendu mon nom mais\r\ntu ne sais pas du tout qui je suis. Alors oui je me suis faite fusillée\r\npour espionnage pendant la Première Guerre mondiale, mais je suis\r\naussi une danseuse et une courtisane de renom. Mon goût pour la\r\nculture est sans équivoque, mes relations et ma faculté d\'écouter\r\naux portes ou de séduire pour obtenir des informations\r\nconfidentielles font de moi une bible de connaissance. Je serais ton\r\nguide, ta compteuse de bonnes aventures, à travers tous les lieux de \r\nstimulations et de controverses culturelles.', 'AiiiiiAIIIIIiiiiiAIIiiiiiiii!!!!!', './images/markers/artB.svg'),
(13, 'art', 'Au pays des grandes roues', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNM80gg41mvc2CwaEFIXO1xqk_za4NrKaeHjDbFzsaqhs7qKJO', 'Un super lieu pour les amateurs de vélo. Tous les outils de réparations disponibles. Venez jouer dans les roues géantes colorées. Des circuits en tricycles pour les tout-petits. C’est ici que vous pouvez louer.', 8, '08:00:00', '20:00:00', 'Oui', 52.375885, 4.898878, 2, 'mata', 'Mijn naam is Mata Ari, tu as certainement déjà entendu mon nom mais\r\ntu ne sais pas du tout qui je suis. Alors oui je me suis faite fusillée\r\npour espionnage pendant la Première Guerre mondiale, mais je suis\r\naussi une danseuse et une courtisane de renom. Mon goût pour la\r\nculture est sans équivoque, mes relations et ma faculté d\'écouter\r\naux portes ou de séduire pour obtenir des informations\r\nconfidentielles font de moi une bible de connaissance. Je serais ton\r\nguide, ta compteuse de bonnes aventures, à travers tous les lieux de \r\nstimulations et de controverses culturelles.', 'AiiiiiAIIIIIiiiiiAIIiiiiiiii!!!!!', './images/markers/artB.svg'),
(18, 'coffee', 'Le Rock shop\r\n', 'https://davesrockshop.com/media/wysiwyg/Rock_Shop_inside_1_900.jpg', 'Situé près de la Leidseplein, le Rookies est un ancien pub reconverti en tout petit coffee-shop. Le visiteur sera donc saisi par la coloration typique de cet ancien pub irlandais, devenu coffee-shop en 1992. L’accès se fait par la rue Korte Leidsedwarstraat. Il faut sortir des sentiers battus pour le trouver, mais il est – signe de qualité – très fréquenté par les locaux. La carte affiche 6 gammes différentes de cannabis et 6 variétés de haschisch. Le café peut accueillir jusqu’à 85 personnes et propose sa propre weed, une indica légère et boisée faite à base de Jack Herrer, une herbe made in Hollande.\r\n', 18, '11:00:00', '20:00:00', 'Oui', 52.363371, 4.891879, 2, 'vincent', 'Tu me connais comme le génie de la peinture le plus dramatique et\r\nromantique.\r\nOui le terme \"Artiste Maudit\" a été inventé pour moi et oui je\r\nsouffre. Mais je suis un génie et je sais ou et comment puiser mon\r\ninspiration. Alors malheureusement nous ne sommes pas à Paris pour\r\nprofiter de la\" Fée verte\" mais à Dam Park où l\'on peut bien abuser des\r\npsychotropes, je serais ton partenaire de fumette, prépare ton bang,\r\nen cette belle journée où tu vas planer sur de la bonne!', 'Je cherche une oreille, vous ne l\'auriez pas vu?', './images/markers/smokegreenG.svg'),
(19, 'coffee', 'Herbe Dance Club \r\n', 'https://i.pinimg.com/564x/58/3a/dd/583add86c194fa2de17ce38b88644435--led-dance-event-management.jpg', 'Voici une antre très réputée des locaux et des badauds qui aiment danser. Malgré un service gonflé de quatre personnes, l’attente au comptoir est souvent longue, et la salle bondée. Il faut être patient, mais cela vaut le coup : au Barneys’s, on sert de l’Utopia Haze et de la G13 Haze. Leurs herbes sont connues pour être très puissantes : consommateurs moins habitués, gare aux effets euphorisants ! \r\n', 18, '08:00:00', '15:00:00', 'Oui', 52.370238, 4.89096, 2, 'vincent', 'Tu me connais comme le génie de la peinture le plus dramatique et\r\nromantique.\r\nOui le terme \"Artiste Maudit\" a été inventé pour moi et oui je\r\nsouffre. Mais je suis un génie et je sais ou et comment puiser mon\r\ninspiration. Alors malheureusement nous ne sommes pas à Paris pour\r\nprofiter de la\" Fée verte\" mais à Dam Park où l\'on peut bien abuser des\r\npsychotropes, je serais ton partenaire de fumette, prépare ton bang,\r\nen cette belle journée où tu vas planer sur de la bonne!', 'Je cherche une oreille, vous ne l\'auriez pas vu?', './images/markers/smokegreenG.svg'),
(20, 'coffee', 'Les tables volantes\r\n', 'http://www.storytrender.com/wp-content/uploads/2017/04/0_CATERS_DINNER_IN_THE_SKY_01-768x576.jpg', 'Vous aviez l’habitude d’avoir peur dans les chaises volantes. Ici, ce n’est pas l’objectif. Les tables volontaires de Dam’Park sont disposées de manière à pouvoir déguster un repas gastronomique dans les airs accompagné de très bonnes weed. Les tables sont en suspensions dans le ciel et permettent de découvrir des plats traditionnels dans les airs. L’odeur de l’herbe se diffuse partout aux alentours\r\n', 16, '12:00:00', '20:00:00', 'Oui', 52.375959, 4.89445, 2, 'vincent', 'Tu me connais comme le génie de la peinture le plus dramatique et\r\nromantique.\r\nOui le terme \"Artiste Maudit\" a été inventé pour moi et oui je\r\nsouffre. Mais je suis un génie et je sais ou et comment puiser mon\r\ninspiration. Alors malheureusement nous ne sommes pas à Paris pour\r\nprofiter de la\" Fée verte\" mais à Dam Park où l\'on peut bien abuser des\r\npsychotropes, je serais ton partenaire de fumette, prépare ton bang,\r\nen cette belle journée où tu vas planer sur de la bonne!', 'Je cherche une oreille, vous ne l\'auriez pas vu?', './images/markers/smokegreenG.svg'),
(21, 'coffee', 'Omelette & Smoke Land\r\n', 'https://ichef.bbci.co.uk/news/660/cpsprodpb/1704/production/_97329850_omelettefrafp.jpg', 'Amateur d’œufs et d’herbe, venez découvrir nos milles recette d’omelettes au haschich au cœur d’un véritable poulailler reconstitué. Laissez-vous picorer les pieds par des poussins qui circulent dans vos jambes alors que vous êtes en train de manger. Idéal pour une pause déjeuner originale et ludique. \r\n', 16, '06:00:00', '18:00:00', 'Oui', 52.374952, 4.904691, 3, 'vincent', 'Tu me connais comme le génie de la peinture le plus dramatique et\r\nromantique.\r\nOui le terme \"Artiste Maudit\" a été inventé pour moi et oui je\r\nsouffre. Mais je suis un génie et je sais ou et comment puiser mon\r\ninspiration. Alors malheureusement nous ne sommes pas à Paris pour\r\nprofiter de la\" Fée verte\" mais à Dam Park où l\'on peut bien abuser des\r\npsychotropes, je serais ton partenaire de fumette, prépare ton bang,\r\nen cette belle journée où tu vas planer sur de la bonne!', 'Je cherche une oreille, vous ne l\'auriez pas vu?', './images/markers/smokegreenG.svg'),
(22, 'coffee', 'Au poisson fumé  \r\n', 'https://media-cdn.tripadvisor.com/media/photo-s/01/16/00/77/the-most-delicious-seafood.jpg', 'Une petite attraction typique de Dam Park qui sert des délicieux harengs pour la modique somme de 3 euros en plus d’un peu d’herbe. Prenez place dans des fauteuils en forme de poissons gigantesques aux nageoires articulées. Levez les yeux, des petites guirlandes de crevettes s’illuminent. Pour vos enfants, une plage artificielle a été créé et des épuisettes sont à leurs dispositions pour qu’ils puissent s’amuser à attraper des crabes. \r\n', 18, '13:00:00', '18:00:00', 'Oui', 52.377874, 4.895142, 3, 'vincent', 'Tu me connais comme le génie de la peinture le plus dramatique et\r\nromantique.\r\nOui le terme \"Artiste Maudit\" a été inventé pour moi et oui je\r\nsouffre. Mais je suis un génie et je sais ou et comment puiser mon\r\ninspiration. Alors malheureusement nous ne sommes pas à Paris pour\r\nprofiter de la\" Fée verte\" mais à Dam Park où l\'on peut bien abuser des\r\npsychotropes, je serais ton partenaire de fumette, prépare ton bang,\r\nen cette belle journée où tu vas planer sur de la bonne!', 'Je cherche une oreille, vous ne l\'auriez pas vu?', './images/markers/smokegreenG.svg'),
(23, 'coffee', 'La grand roues Donuts \r\n', 'https://i.pinimg.com/736x/6e/97/1e/6e971e473c8a95d6db3315e47fd005c0--donut-shop-donuts.jpg', 'Prenez de l’altitude pour déguster de succulents Donut’s accompagné d’herbe. Dans la file d’attente, un homme vous propose une centaine de variété de donut’s et d’herbes dans un petit chariot doré. Une fois sélectionnés, prenez place dans la grande roue. Les tours durent plus de 10 minutes et vous permettent d’admirer les toits de Dam’Park. \r\n', 14, '10:00:00', '15:00:00', 'Non', 52.370145, 4.895158, 3, 'vincent', 'Tu me connais comme le génie de la peinture le plus dramatique et\r\nromantique.\r\nOui le terme \"Artiste Maudit\" a été inventé pour moi et oui je\r\nsouffre. Mais je suis un génie et je sais ou et comment puiser mon\r\ninspiration. Alors malheureusement nous ne sommes pas à Paris pour\r\nprofiter de la\" Fée verte\" mais à Dam Park où l\'on peut bien abuser des\r\npsychotropes, je serais ton partenaire de fumette, prépare ton bang,\r\nen cette belle journée où tu vas planer sur de la bonne!', 'Je cherche une oreille, vous ne l\'auriez pas vu?', './images/markers/smokegreenG.svg'),
(24, 'eat', 'La maison de l’houmous crémeux \r\n', 'http://i.cdn.turner.com/cnn/2010/WORLD/meast/05/09/lebanon.hummus/t1larg.jpg', '\r\nCette petite maison est nichée au cœur d’une forêt d’arbustes à pois chiche. Découvrez l’envers du décor de la fabrication de l’houmous. Participez à toutes les étapes du broyage manuel et laissez-vous surprendre par les galettes géantes au sarrasin. \r\n', 12, '12:00:00', '19:00:00', 'Non', 52.376456, 4.899601, 1, 'houten', 'Welkom je suis Carice van Houten. Tu ne m\'as peut être pas reconnu\r\nau premier coup d\'oeil. Habituellement, j\'ai les cheveux rouges et\r\nje suis plûtot dénudée, ça te parle d\'avantage? J\'ai tendance à\r\npousser les gens à tuer des personnes de leur famille et je fais de\r\nla magie Rouge. Banco, je suis la prêtresse rouge dans Game of\r\nThrones! Aujourd\'hui je suis ton guide et je vais t\'amener festoyer\r\ndans des tavernes dont les mets et breuvages dépassent\r\nl\'entendement, alors prépare toi car tu vas t\'apprêter à toucher\r\nl\'Olympe!!!!', 'Sniff Sniff, voici de la poudre de Perlinpinpin!', './images/markers/eatB.svg'),
(25, 'eat', 'Le bol de soupe géant \r\n', 'http://travelwithbender.com/files/1914/3325/1634/canggu_club_IMG_4494-2.jpg', '\r\nPiscine en forme de bol à déjeuner géant dans laquelle petits et grands peuvent se prélasser. En fonction des saisons, la piscine change de couleur : verte-salade l’été et rouge-tomate l’hiver. En plus de la couleur, cette piscine dégage un léger parfum de vacances. Maillot de bain obligatoire. \r\n', 12, '08:00:00', '15:00:00', 'Non', 52.371549, 4.902603, 1, 'houten', 'Welkom je suis Carice van Houten. Tu ne m\'as peut être pas reconnu\r\nau premier coup d\'oeil. Habituellement, j\'ai les cheveux rouges et\r\nje suis plûtot dénudée, ça te parle d\'avantage? J\'ai tendance à\r\npousser les gens à tuer des personnes de leur famille et je fais de\r\nla magie Rouge. Banco, je suis la prêtresse rouge dans Game of\r\nThrones! Aujourd\'hui je suis ton guide et je vais t\'amener festoyer\r\ndans des tavernes dont les mets et breuvages dépassent\r\nl\'entendement, alors prépare toi car tu vas t\'apprêter à toucher\r\nl\'Olympe!!!!', 'Sniff Sniff, voici de la poudre de Perlinpinpin!', './images/markers/eatB.svg'),
(26, 'eat', 'Le champignon hanté \r\n', 'http://i2.wp.com/amazingbeautifulworld.com/wp-content/uploads/2013/05/Giant-mushroom-in-Oregon.jpg', 'Ce champignon qui est apparu 1823 est toujours vivant. On y entre par une petite porte et il possède de jolies petites tâches. Mais derrière cette image idyllique se cache une histoire plus sombre. La demeure serait habitée par le fantôme d’un cueilleur de champignons. Au début du XXe siècle, ce dernier est sauvagement assassinée. Son bourreau ne sera jamais retrouvé, laissant l’âme du cueilleur rodée dans ce champignon géant. A l’intérieur, on y déguste de merveilleux plats aux cèpes et girolles dans de grands fauteuils en velours gris en forme de coulemelles. \r\n', 10, '13:00:00', '15:00:00', 'Non', 52.368541, 4.897123, 2, 'houten', 'Welkom je suis Carice van Houten. Tu ne m\'as peut être pas reconnu\r\nau premier coup d\'oeil. Habituellement, j\'ai les cheveux rouges et\r\nje suis plûtot dénudée, ça te parle d\'avantage? J\'ai tendance à\r\npousser les gens à tuer des personnes de leur famille et je fais de\r\nla magie Rouge. Banco, je suis la prêtresse rouge dans Game of\r\nThrones! Aujourd\'hui je suis ton guide et je vais t\'amener festoyer\r\ndans des tavernes dont les mets et breuvages dépassent\r\nl\'entendement, alors prépare toi car tu vas t\'apprêter à toucher\r\nl\'Olympe!!!!', 'Sniff Sniff, voici de la poudre de Perlinpinpin!', './images/markers/eatB.svg'),
(27, 'eat', 'Karting sushis\r\n', 'https://5f7mk98d5d69eqvo-zippykid.netdna-ssl.com/wp-content/uploads/2015/09/sushi-river-3.jpg', '\r\nConduisez de véritables karts en forme de sushis géants. Un parcours de 5km dans la ville d’Amsterdam au volant de ces incroyables bolides. Une nouvelle manière de découvrir la ville. Ces véhicules vous permettent d’aller à plus de 50km/h et de sillonner les meilleures attractions. Des courses sont organisées deux fois par jour. Réservez dès maintenant en envoyant un Poke à Joël. \r\n', 16, '10:00:00', '20:00:00', 'Oui', 52.360869, 4.880477, 2, 'houten', 'Welkom je suis Carice van Houten. Tu ne m\'as peut être pas reconnu\r\nau premier coup d\'oeil. Habituellement, j\'ai les cheveux rouges et\r\nje suis plûtot dénudée, ça te parle d\'avantage? J\'ai tendance à\r\npousser les gens à tuer des personnes de leur famille et je fais de\r\nla magie Rouge. Banco, je suis la prêtresse rouge dans Game of\r\nThrones! Aujourd\'hui je suis ton guide et je vais t\'amener festoyer\r\ndans des tavernes dont les mets et breuvages dépassent\r\nl\'entendement, alors prépare toi car tu vas t\'apprêter à toucher\r\nl\'Olympe!!!!', 'Sniff Sniff, voici de la poudre de Perlinpinpin!', './images/markers/eatB.svg'),
(28, 'eat', '\r\nLes montagnes au Chewing-gum\r\n', 'http://www.turismoroma.it/wp-content/uploads/2011/07/Montagne-russe-Rainbow-Magicland.jpg', '\r\nVous connaissiez les montagnes russes ? Découvrez aujourd’hui le grand huit de Dam’Park, une attraction construite intégralement en Chewing-gum dur et cristallisé. Cette attraction a été breveté par un laboratoire d’ingénierie japonais pour vous garantir une sécurité optimale. Des Chewing-gum au parfum originaux sont disponibles à la sortie. Cette attraction est considérée comme la plus vertigineuses de tous les temps par le Guinness des Records 2017.\r\n', 12, '11:00:00', '19:00:00', 'Oui', 52.356033, 4.884318, 3, 'houten', 'Welkom je suis Carice van Houten. Tu ne m\'as peut être pas reconnu\r\nau premier coup d\'oeil. Habituellement, j\'ai les cheveux rouges et\r\nje suis plûtot dénudée, ça te parle d\'avantage? J\'ai tendance à\r\npousser les gens à tuer des personnes de leur famille et je fais de\r\nla magie Rouge. Banco, je suis la prêtresse rouge dans Game of\r\nThrones! Aujourd\'hui je suis ton guide et je vais t\'amener festoyer\r\ndans des tavernes dont les mets et breuvages dépassent\r\nl\'entendement, alors prépare toi car tu vas t\'apprêter à toucher\r\nl\'Olympe!!!!', 'Sniff Sniff, voici de la poudre de Perlinpinpin!', './images/markers/eatB.svg'),
(29, 'eat', 'La bicyclette fruitée \r\n', 'https://thumbs.dreamstime.com/b/tienda-o-verduler%C3%ADa-de-la-fruta-de-la-bicicleta-en-la-calle-en-el-mercado-de-thamel-47549316.jpg', '\r\nEmprunté un vélo hollandais traditionnel pour parcourir les champs de poiriers, pommiers et fraisiers. Chaque vélo est équipé d’un panier en osier vous permettant de récolter des kilos de fruits. Plusieurs parcours sont disponibles pour permettre aux petits et grands de découvrir les paysages de Dam’park. Des sièges enfants sont disponibles. \r\n', 18, '11:00:00', '15:00:00', 'Non', 52.356726, 4.897434, 2, 'houten', 'Welkom je suis Carice van Houten. Tu ne m\'as peut être pas reconnu\r\nau premier coup d\'oeil. Habituellement, j\'ai les cheveux rouges et\r\nje suis plûtot dénudée, ça te parle d\'avantage? J\'ai tendance à\r\npousser les gens à tuer des personnes de leur famille et je fais de\r\nla magie Rouge. Banco, je suis la prêtresse rouge dans Game of\r\nThrones! Aujourd\'hui je suis ton guide et je vais t\'amener festoyer\r\ndans des tavernes dont les mets et breuvages dépassent\r\nl\'entendement, alors prépare toi car tu vas t\'apprêter à toucher\r\nl\'Olympe!!!!', 'Sniff Sniff, voici de la poudre de Perlinpinpin!', './images/markers/eatB.svg');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `attractions`
--
ALTER TABLE `attractions`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `THEME` (`THEME`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `attractions`
--
ALTER TABLE `attractions`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=30;COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
